from __future__ import annotations

import os
from typing import Optional

import pandas as pd

from .data_io import write_csv, ensure_dir


def _html_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def save_daily_report(
    universe_snap: pd.DataFrame,
    picks: pd.DataFrame,
    report_dir: str,
    date_str: str,
) -> str:
    # Save CSVs
    write_csv(universe_snap, os.path.join(report_dir, "universe.csv"))
    write_csv(picks, os.path.join(report_dir, "picks.csv"))

    # Build minimal HTML
    top_rows = picks[[c for c in ["symbol", "close", "strength_score", "vol_z", "ab_vol"] if c in picks.columns]].copy()
    # Round numeric columns for readability
    for c in ["close", "strength_score", "vol_z"]:
        if c in top_rows.columns:
            top_rows[c] = top_rows[c].astype(float).round(4)

    table_html = """
    <table>
      <thead>
        <tr>
          {headers}
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    """
    headers = "".join(f"<th>{_html_escape(str(h))}</th>" for h in top_rows.columns)
    row_html = "".join(
        "<tr>" + "".join(f"<td>{_html_escape(str(v))}</td>" for v in row) + "</tr>"
        for row in top_rows.itertuples(index=False)
    )

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>A-share Daily Report - {date_str}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 20px; }}
    h1 {{ font-size: 1.6rem; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: right; }}
    th {{ background-color: #f4f4f4; }}
    td:first-child, th:first-child {{ text-align: left; }}
    .meta {{ color: #666; margin-bottom: 10px; }}
    .links a {{ margin-right: 10px; }}
  </style>
</head>
<body>
  <h1>A-share Daily Report</h1>
  <div class="meta">Date: {date_str} | Universe size: {len(universe_snap)}</div>
  <div class="links">
    <a href="universe.csv">universe.csv</a>
    <a href="picks.csv">picks.csv</a>
  </div>
  <h2>Top Picks</h2>
  {table}
  <hr />
  <div class="meta">Generated by Astock: A-share analyzer</div>
</body>
</html>
""".format(date_str=_html_escape(date_str), table=table_html.format(headers=headers, rows=row_html))

    out_path = os.path.join(report_dir, "report.html")
    ensure_dir(report_dir)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path
